[webservers]
web-1 ansible_host= fqdn=fhmn1208e91jukc610mk.auto.internal
web-2 ansible_host= fqdn=fhm7898kc5mtrmln6r3i.auto.internal
[databases]
main ansible_host= fqdn=fhm3fk6a3qu71grtkh0r.auto.internal
replica ansible_host= fqdn=fhmg6gv0vtgp0mmad1qq.auto.internal
[storage]
storage ansible_host= fqdn=fhmhcbjf2o92d44eg9mk.auto.internal