---
roles:
  - name: lighthouse-role
    src: https://github.com/hiriyanovmm/lighthouse-role.git
    scm: git
    version: "1.0.0"

  - name: vector-role
    src: https://github.com/hiriyanovmm/vector-role.git
    scm: git
    version: "1.0.0"

  - name: clickhouse
    src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    