---
- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart vector service
  become: true
  ansible.builtin.service:
    name: vector
    state: restarted
  tags:
    - vector
  when: vector_manage_service | bool

