---
galaxy_info:
  author: Mikhail Hiriyanov
  description: Ansible role for installing and configuring Vector
  license: MIT
  min_ansible_version: "2.12"

  platforms:
    - name: EL
      versions:
        - 8
        - 9

  galaxy_tags:
    - vector
    - logging
    - monitoring
    - observability

dependencies: []