---
- name: Add Vector repository
  become: true
  tags:
    - vector
    - vector:repository
    - vector:install
  ansible.builtin.shell: |
    bash -c "$(curl -L https://setup.vector.dev)"
  args:
    creates: /etc/yum.repos.d/vector.repo

- name: Refresh package cache
  become: true
  tags:
    - vector
    - vector:repository
    - vector:install
  ansible.builtin.yum:
    update_cache: true

- name: Install Vector package
  become: true
  tags:
    - vector
    - vector:package
    - vector:install
  ansible.builtin.yum:
    name: vector
    state: present

- name: Create Vector config directory
  become: true
  tags:
    - vector
    - vector:directories
    - vector:install
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: "0755"

- name: Deploy Vector config
  become: true
  tags:
    - vector
    - vector:config
    - vector:deploy
  ansible.builtin.template:
    src: vector.yaml.j2
    dest: "{{ vector_config_path }}"
    owner: vector
    group: vector
    mode: "0640"
    validate: "/usr/bin/vector validate --config-yaml %s"
  notify: Restart vector service

- name: Enable and start Vector service
  become: true
  tags:
    - vector
    - vector:service
    - vector:install
  ansible.builtin.service:
    name: vector
    state: started
    enabled: true