---
- name: Download Vector installer
  tags:
    - vector
  ansible.builtin.get_url:
    url: https://sh.vector.dev
    dest: /tmp/vector-installer.sh
    mode: "0755"

- name: Install Vector via installer
  tags:
    - vector
  become: true
  ansible.builtin.command:
    cmd: /tmp/vector-installer.sh -y
  environment:
    VECTOR_VERSION: "{{ vector_version }}"
  register: vector_install
  changed_when: "'already installed' not in (vector_install.stdout | lower)"

# - name: Check vector binary
#   tags:
#    - vector
#   ansible.builtin.command: vector --version
#   register: vector_version_check
#   changed_when: false

#  - name: Create Vector config directory
#    tags:
#     - vector
#   become: true
#   ansible.builtin.file:
#     path: /etc/vector
#     state: directory
#     mode: '0755'

# - name: Deploy Vector config
#   tags:
#    - vector
#   become: true
#   ansible.builtin.template:
#     src: vector.toml.j2
#     dest: /etc/vector/vector.toml
#     mode: '0644'
#   notify: Restart vector service

# - name: Enable and start vector service
#   tags:
#    - vector
#   become: true
#   ansible.builtin.service:
#     name: vector
#     state: started
#     enabled: true